"""Tests for field extensions and Galois group construction."""

import numpy as np
import pytest
from fractions import Fraction

from galois_cohomology.fields import (
    QuadraticField,
    CyclotomicField,
    _euler_totient,
    _cyclotomic_polynomial,
)
from galois_cohomology.modules import GModule


class TestEulerTotient:
    def test_primes(self):
        assert _euler_totient(2) == 1
        assert _euler_totient(3) == 2
        assert _euler_totient(5) == 4
        assert _euler_totient(7) == 6

    def test_prime_powers(self):
        assert _euler_totient(4) == 2
        assert _euler_totient(8) == 4
        assert _euler_totient(9) == 6

    def test_composites(self):
        assert _euler_totient(6) == 2
        assert _euler_totient(12) == 4


class TestCyclotomicPolynomial:
    def test_phi_1(self):
        # Phi_1(x) = x - 1
        assert _cyclotomic_polynomial(1) == [-1, 1]

    def test_phi_2(self):
        # Phi_2(x) = x + 1
        assert _cyclotomic_polynomial(2) == [1, 1]

    def test_phi_3(self):
        # Phi_3(x) = x^2 + x + 1
        assert _cyclotomic_polynomial(3) == [1, 1, 1]

    def test_phi_4(self):
        # Phi_4(x) = x^2 + 1
        assert _cyclotomic_polynomial(4) == [1, 0, 1]

    def test_phi_5(self):
        # Phi_5(x) = x^4 + x^3 + x^2 + x + 1
        assert _cyclotomic_polynomial(5) == [1, 1, 1, 1, 1]

    def test_phi_6(self):
        # Phi_6(x) = x^2 - x + 1
        assert _cyclotomic_polynomial(6) == [1, -1, 1]


class TestQuadraticField:
    def test_galois_group(self):
        K = QuadraticField(d=2)
        G = K.galois_group()
        assert G.order == 2
        assert G.validate()

    def test_conjugate(self):
        K = QuadraticField(d=5)
        # 3 + 2*sqrt(5) -> 3 - 2*sqrt(5)
        elem = (Fraction(3), Fraction(2))
        conj = K.conjugate(elem)
        assert conj == (Fraction(3), Fraction(-2))

    def test_multiplicative_module_valid(self):
        K = QuadraticField(d=3)
        M = K.multiplicative_module()
        assert M.validate()
        assert M.rank == 2

    def test_sigma_squares_to_identity(self):
        K = QuadraticField(d=7)
        M = K.multiplicative_module()
        sigma = M.action(1)
        assert np.array_equal(sigma @ sigma, np.eye(2, dtype=np.int64))


class TestCyclotomicField:
    def test_degree(self):
        assert CyclotomicField(3).degree == 2
        assert CyclotomicField(4).degree == 2
        assert CyclotomicField(5).degree == 4
        assert CyclotomicField(7).degree == 6

    def test_galois_group_order(self):
        """Gal(Q(zeta_n)/Q) has order phi(n)."""
        for n in [3, 4, 5, 7]:
            F = CyclotomicField(n)
            G = F.galois_group()
            assert G.order == _euler_totient(n)
            assert G.validate()

    def test_galois_group_cyclic_for_prime(self):
        """Gal(Q(zeta_p)/Q) = (Z/pZ)* is cyclic of order p-1."""
        F = CyclotomicField(5)
        G = F.galois_group()
        assert G.order == 4
        # (Z/5Z)* = {1,2,3,4} under mult mod 5, cyclic generated by 2
        assert G.validate()

    def test_action_matrix_identity(self):
        """sigma_1 should be the identity matrix."""
        F = CyclotomicField(5)
        mat = F.galois_action_matrix(1)
        assert np.array_equal(mat, np.eye(4, dtype=np.int64))

    def test_standard_module_valid(self):
        """The standard module should have a valid G-action."""
        for n in [3, 4, 5]:
            F = CyclotomicField(n)
            M = F.standard_module()
            assert M.validate(), f"Standard module invalid for n={n}"

    def test_action_matrix_for_zeta3(self):
        """
        Q(zeta_3) has basis {1, zeta_3}. Phi_3 = x^2 + x + 1.
        sigma_2: zeta_3 -> zeta_3^2 = -zeta_3 - 1 (by minimal polynomial).
        So sigma_2 on basis {1, zeta}: 1 -> 1, zeta -> -1 - zeta.
        Matrix: [[1, -1], [0, -1]]
        """
        F = CyclotomicField(3)
        mat = F.galois_action_matrix(2)
        expected = np.array([[1, -1], [0, -1]], dtype=np.int64)
        assert np.array_equal(mat, expected)
