"""
Tate cohomology for finite groups.

For a finite group G and G-module M, Tate cohomology extends ordinary
group cohomology to negative degrees:

    H^n_T(G, M) = H^n(G, M)           for n >= 1
    H^0_T(G, M) = M^G / N(M)          (fixed points mod norm image)
    H^{-1}_T(G, M) = ker(N) / I_G M   (norm kernel mod augmentation ideal image)
    H^{-n}_T(G, M) = H_{n-1}(G, M)    for n >= 2 (group homology)

For cyclic groups, Tate cohomology is 2-periodic: H^n_T = H^{n+2}_T.
The Herbrand quotient h(G, M) = |H^0_T| / |H^{-1}_T| is a key invariant.
"""

from __future__ import annotations

import numpy as np
from dataclasses import dataclass

from .modules import FiniteGroup, GModule
from .cohomology import compute_cohomology, CohomologyGroup, fixed_points
from .applications import NormMap
from .utils import smith_normal_form, kernel_basis


@dataclass
class TateCohomologyGroup:
    """Tate cohomology group H^n_T(G, M)."""

    degree: int
    free_rank: int
    torsion_invariants: list[int]

    @property
    def order(self) -> int | None:
        if self.free_rank > 0:
            return None
        if not self.torsion_invariants:
            return 1
        result = 1
        for d in self.torsion_invariants:
            result *= d
        return result

    @property
    def is_trivial(self) -> bool:
        return self.free_rank == 0 and len(self.torsion_invariants) == 0

    def __repr__(self) -> str:
        parts = []
        if self.free_rank > 0:
            parts.append(f"Z^{self.free_rank}" if self.free_rank > 1 else "Z")
        for d in self.torsion_invariants:
            parts.append(f"Z/{d}Z")
        if not parts:
            return f"H^{self.degree}_T = 0"
        return f"H^{self.degree}_T = {' + '.join(parts)}"


def tate_h0(group: FiniteGroup, module: GModule) -> TateCohomologyGroup:
    """
    Compute H^0_T(G, M) = M^G / N(M).

    M^G = fixed points, N = norm map (sum of all g).
    """
    fp = fixed_points(group, module)
    norm = NormMap.build(group, module)

    # M^G is spanned by columns of fp (in the ambient Z^rank)
    # N(M) is the image of the norm map, intersected with M^G
    # H^0_T = M^G / (N(M) cap M^G)

    # Since N(M) is contained in M^G (norm of anything is G-fixed),
    # we just need M^G / im(N)
    # Express im(N) in the basis of M^G
    from .cohomology import _express_in_basis
    norm_image = norm.matrix  # columns generate im(N) in Z^rank

    if fp.shape[1] == 0:
        return TateCohomologyGroup(degree=0, free_rank=0, torsion_invariants=[])

    # Express norm image columns in the M^G basis
    coord = _express_in_basis(fp, norm_image)
    if coord is None or coord.size == 0:
        # im(N) = 0 in M^G, so H^0_T = M^G
        return TateCohomologyGroup(
            degree=0, free_rank=fp.shape[1], torsion_invariants=[]
        )

    snf = smith_normal_form(coord)
    torsion = [d for d in snf.invariant_factors if d > 1]
    rank_of_im = len(snf.invariant_factors)
    free_rank = fp.shape[1] - rank_of_im

    return TateCohomologyGroup(degree=0, free_rank=free_rank, torsion_invariants=torsion)


def tate_hminus1(group: FiniteGroup, module: GModule) -> TateCohomologyGroup:
    """
    Compute H^{-1}_T(G, M) = ker(N) / I_G.M.

    I_G = augmentation ideal of Z[G], generated by {g - 1 : g in G}.
    I_G.M is spanned by {(g-1).m : g in G, m in standard basis of M}.
    """
    r = module.rank
    norm = NormMap.build(group, module)

    # ker(N): kernel of the norm matrix
    ker_N = kernel_basis(norm.matrix)

    if ker_N.shape[1] == 0:
        return TateCohomologyGroup(degree=-1, free_rank=0, torsion_invariants=[])

    # I_G.M: spanned by (g-1).e_j for all g in G, j in {0,...,r-1}
    # (g-1) acts as action(g) - I on M
    ig_generators = []
    identity = np.eye(r, dtype=np.int64)
    for g in range(group.order):
        diff = module.action(g) - identity
        for j in range(r):
            ig_generators.append(diff[:, j])

    if not ig_generators:
        return TateCohomologyGroup(
            degree=-1, free_rank=ker_N.shape[1], torsion_invariants=[]
        )

    ig_matrix = np.column_stack(ig_generators)

    # H^{-1}_T = ker(N) / (I_G.M cap ker(N))
    # Since I_G.M is contained in ker(N) (norm kills augmentation ideal image),
    # we just need ker(N) / I_G.M
    from .cohomology import _express_in_basis
    coord = _express_in_basis(ker_N, ig_matrix)

    if coord is None or coord.size == 0:
        return TateCohomologyGroup(
            degree=-1, free_rank=ker_N.shape[1], torsion_invariants=[]
        )

    snf = smith_normal_form(coord)
    torsion = [d for d in snf.invariant_factors if d > 1]
    rank_of_im = len(snf.invariant_factors)
    free_rank = ker_N.shape[1] - rank_of_im

    return TateCohomologyGroup(degree=-1, free_rank=free_rank, torsion_invariants=torsion)


def herbrand_quotient(group: FiniteGroup, module: GModule) -> tuple[int, int] | None:
    """
    Compute the Herbrand quotient h(G, M) = |H^0_T| / |H^{-1}_T|.

    Returns (numerator, denominator) or None if either group is infinite.
    Only well-defined for cyclic groups (and always equals |G| for
    finite modules in that case, by periodicity).
    """
    h0 = tate_h0(group, module)
    hm1 = tate_hminus1(group, module)

    if h0.order is None or hm1.order is None:
        return None

    return (h0.order, hm1.order)
